#!/bin/bash

# Get current script path
SCRIPT_PATH="$( dirname -- "$( readlink -f -- "${0}"; )"; )"
# Activate OctoDNS Python venv
source "${SCRIPT_PATH}/common.sh"

SOURCES=$(find *.py octodns_* tests -name "*.py")

isort "$@" $SOURCES
black "$@" $SOURCES
